### ISSUE TITLE
Stop storing Whitehall assets directly on the NFS mount

### ISSUE THREAD

**Issue by floehopper** [alphagov/asset-manager#231] opened 2017-09-25 13:49 UTC
Once we're serving all non-attachment Whitehall assets from Asset Manager, we'll be able to stop storing these assets directly on the NFS mount.

**Comment by chrislo** [comment] 2018-01-29 14:18
In the context of this milestone I think this issue is a duplicate of https://github.com/alphagov/asset-manager/issues/424.

**Closed by chrislo** 2018-01-29 14:18 UTC
