### ISSUE TITLE
.odt files aren't served with the correct mimetype

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/asset-manager#417] opened 2018-01-18 13:46 UTC
The .odt file linked from https://www.gov.uk/government/consultations/great-western-rail-franchise 
(https://assets.publishing.service.gov.uk/government/uploads/system/uploads/consultation_response_form_data/file/629/great-western-consultation.odt) is served with `Content-Type: application/octet-stream`. This is causing some combinations of Windows and IE, particularly at DfT, to download the file with a .zip extension. Users are then not able to open the file without renaming to .odt.

**Comment by chrisroos** [comment] 2018-01-18 14:09
Thanks @boffbowsh. I suspect this might be related to "Investigate content-type difference between Whitehall and Asset Manager #408".

**Comment by chrisroos** [comment] 2018-01-19 08:35
I'm going to investigate this as the problem will only get worse as we migrate more Whitehall assets to Asset Manager.

**Comment by chrisroos** [comment] 2018-01-19 08:58
The difference in behaviour between Whitehall and Asset Manager is caused by the [additional mime types that have been added to Whitehall](https://github.com/alphagov/whitehall/blob/master/config/initializers/mime_types.rb).

We can observe the problem by comparing an Asset Manager Rails console to a Whitehall Rails console:

```
# Asset Manager
> Mime::Type.lookup_by_extension('odt')
=> nil

# Whitehall
> Mime::Type.lookup_by_extension('odt')
=> #<Mime::Type:0x0000556910e84a58 @hash=1499320519752563818, @string="application/vnd.oasis.opendocument.text", @symbol=:odt, @synonyms=[]>
```

**Comment by chrisroos** [comment] 2018-01-19 10:28
I've opened https://github.com/alphagov/asset-manager/pull/418 to address this issue.

**Comment by chrisroos** [comment] 2018-01-19 12:27
I've merged https://github.com/alphagov/asset-manager/pull/418 so I'll test the effect on integration once it's been deployed.

**Comment by chrisroos** [comment] 2018-01-19 12:50
I've tested this in integration by uploading a .odt file and requesting it using curl:

```
$ curl -v "https://assets-origin.integration.publishing.service.gov.uk/media/5a61e8f15f743b5834d6087b/great-western-consultation.odt" > /dev/null

> GET /media/5a61e8f15f743b5834d6087b/great-western-consultation.odt HTTP/2
> Host: assets-origin.integration.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Fri, 19 Jan 2018 12:48:04 GMT
< content-type: application/vnd.oasis.opendocument.text
< content-length: 68217
< server: nginx
< accept-ranges: bytes
< cache-control: max-age=86400, public
< content-disposition: inline; filename="great-western-consultation.odt"
< etag: "5a61e8f1-10a79"
< last-modified: Fri, 19 Jan 2018 12:47:45 GMT
< strict-transport-security: max-age=31536000
< x-frame-options: DENY
< access-control-allow-origin: *
< access-control-allow-methods: GET, OPTIONS
< access-control-allow-headers: origin, authorization
```

Note that the `content-type` header is set to `application/vnd.oasis.opendocument.text` so I'm happy that this has worked as expected.

I'll get Asset Manager deployed to production.

**Comment by chrisroos** [comment] 2018-01-19 14:06
This has been merged to production and I've confirmed that we're now seeing the correct `content-type` when requesting the asset in the description of the issue.

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/consultation_response_form_data/file/629/great-western-consultation.odt?123" > /dev/null

> GET /government/uploads/system/uploads/consultation_response_form_data/file/629/great-western-consultation.odt?123 HTTP/1.1
> Host: assets.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/vnd.oasis.opendocument.text
< Content-Disposition: inline; filename="great-western-consultation.odt"
< Cache-Control: max-age=14400, public
< ETag: "5a1d35db-10a79"
< Last-Modified: Tue, 28 Nov 2017 10:09:31 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 68217
< Accept-Ranges: bytes
< Date: Fri, 19 Jan 2018 14:02:35 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lcy19228-LCY
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1516370555.119605,VS0,VE184
```

Note the use of the querystring in my `curl` command to break the cache. The version of this file that's cached by Fastly will continue to contain the incorrect `content-type` until the cache is refreshed. I'm going to leave this issue open and check again on Monday when I expect the cached copy to have expired.

**Comment by chrisroos** [comment] 2018-01-29 11:39
I've just requested this asset again and confirmed that the version cached at Fastly contains the correct `Content-Type`:

```
$ curl -v "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/consultation_response_form_data/file/629/great-western-consultation.odt" > /dev/null

> GET /government/uploads/system/uploads/consultation_response_form_data/file/629/great-western-consultation.odt HTTP/1.1
> Host: assets.publishing.service.gov.uk
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: application/vnd.oasis.opendocument.text
< Content-Disposition: inline; filename="great-western-consultation.odt"
< Cache-Control: max-age=14400, public
< ETag: "5a1d35db-10a79"
< Last-Modified: Tue, 28 Nov 2017 10:09:31 GMT
< X-Frame-Options: SAMEORIGIN
< Strict-Transport-Security: max-age=31536000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Allow-Headers: origin, authorization
< Fastly-Backend-Name: origin
< Content-Length: 68217
< Accept-Ranges: bytes
< Date: Mon, 29 Jan 2018 11:38:03 GMT
< Via: 1.1 varnish
< Age: 0
< Connection: keep-alive
< X-Served-By: cache-lhr6343-LHR
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Timer: S1517225883.169775,VS0,VE94
```

This all looks good so I'm closing this issue.

**Closed by chrisroos** 2018-01-29 11:39 UTC
Labels: bug
